version: '1.0'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend/backend.conf:/app/backend.conf
    restart: unless-stopped
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./frontend/src/.env
    volumes:
      - ./frontend/frontend.conf:/app/frontend.conf
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "1234:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
    depends_on:
      - frontend
      - backend

